/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_sison_android_nodejs_repl_NodeJNI */

#ifndef _Included_nl_sison_android_nodejs_repl_NodeJNI
#define _Included_nl_sison_android_nodejs_repl_NodeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_sison_android_nodejs_repl_NodeJNI
 * Method:    redirectStdio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_nl_sison_android_nodejs_repl_NodeJNI_redirectStdio
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     nl_sison_android_nodejs_repl_NodeJNI
 * Method:    stopRedirect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_nl_sison_android_nodejs_repl_NodeJNI_stopRedirect
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     nl_sison_android_nodejs_repl_NodeJNI
 * Method:    start
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_nl_sison_android_nodejs_repl_NodeJNI_start
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
